version: "3.1"
services:

    postgis:
      image: kartoza/postgis:10.0-2.4
      container_name: postgis
      env_file: .env
      environment:
        - PGDATA=/var/lib/postgresql/data
        - ALLOW_IP_RANGE=0.0.0.0/0
      volumes:
        - ${APP_DIR}/pgdata:/var/lib/postgresql/data:rw
        - ${APP_DIR}/pglogs:/srv/gis/data/logs:rw
        - ./conf/psql_overrides.conf:/etc/postgresql/10/main/conf.d/psql_overrides.conf:rw
      networks:
        dock_net:
          ipv4_address: 10.5.0.10

    osm:
      build: osm
      container_name: osm
      env_file: .env
      volumes:
        - ${APP_DIR}/tiles:/var/lib/mod_tile:rw
        - ${APP_DIR}/import:/import:rw
        - ./conf/project.mml:/home/renderer/src/openstreetmap-carto/project.mml.template
      command: run
      networks:
        dock_net:
          ipv4_address: 10.5.0.15

    osmimport:
      build: osm
      container_name: osmimport
      env_file: .env
      volumes:
        - ${APP_DIR}/import:/import:rw
        - ${APP_DIR}/tiles:/var/lib/mod_tile:rw
        #- ./conf/project.mml:/home/renderer/src/openstreetmap-carto/project.mml.template
      command: import
      networks:
        dock_net:
          ipv4_address: 10.5.0.20

    osrm:
      image: cartography/osrm-backend-docker:latest
      container_name: osrm
      env_file: .env
      volumes:
        - ${APP_DIR}/import:/import:rw
      command: osrm London "http://download.geofabrik.de/europe/great-britain/england/greater-london-latest.osm.pbf"
      networks:
        dock_net:
          ipv4_address: 10.5.0.25

networks:
  dock_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/24

